# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
    build:
      working_directory: ~/dyno-ts
      docker:
          - image: circleci/node:6.10.3
      steps:
          - checkout
          # Download and cache dependencies
          - restore_cache:
              keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  # fallback to using the latest cache if no exact match is found
                  - v1-dependencies-

          - run:
              name: install java
              command: sudo apt-get update && sudo apt-get install -y openjdk-7-jre && sudo rm -rf /var/lib/apt/lists/*

          - run:
              name: yarn
              command: yarn

          - save_cache:
              paths:
                  - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}

          - run:
              name: lint
              command: yarn run lint

          - run:
              name: Test
              command: yarn run test:coverage

          - run:
              name: Upload coverage report
              command: bash <(curl -s https://codecov.io/bash)

          - store_artifacts:
              path: coverage
              prefix: coverage
